version: "3.8"

services:
  app:
    build: .
    image: vercel-fastapi-sample-app
    container_name: vercel-fastapi-sample-app
    command: python -m main
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/app
    working_dir: /app
